# https://taskfile.dev

version: '3'

tasks:
  pb:
    cmds:
      - protoc -I . -I ${GOPATH}/src -I ${GOPATH}/src/github.com/envoyproxy/protoc-gen-validate --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative --validate_out="lang=go:./proto" --grpc-gateway_out . --grpc-gateway_opt logtostderr=true --grpc-gateway_opt paths=source_relative  --grpc-gateway_opt generate_unbound_methods=true --openapiv2_out . --openapiv2_opt logtostderr=true --openapiv2_opt generate_unbound_methods=true proto/*.proto

#  protoc -I .
#  proto/*.proto


  main:
    cmds:
      - go build .
      - ./supernova main

  execute-migration:
    cmds:
      - go build .
      - ./supernova execute-migration

  generate-migration:
    cmds:
      - go build .
      - ./supernova generate-migration
      - go generate ./ent

  validate-migration:
    cmds:
      - ./atlas-linux-amd64 migrate validate migrations

  rehash-migration:
    cmds:
      - ./atlas-linux-amd64 migrate hash --force