# https://taskfile.dev

version: '3'

tasks:
  pb:
    cmds:
      - protoc -I . -I ${GOPATH}/src -I ${GOPATH}/src/github.com/envoyproxy/protoc-gen-validate --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative --validate_out="lang=go:./proto" proto/*.proto

  main:
    cmds:
      - go build .
      - ./supernova main

  execute-migration:
    cmds:
      - go build .
      - ./supernova execute-migration

  generate-migration:
    cmds:
      - go build .
      - ./supernova generate-migration
      - go generate ./ent

  validate-migration:
    cmds:
      - ./atlas-linux-amd64 migrate validate migrations

  rehash-migration:
    cmds:
      - ./atlas-linux-amd64 migrate hash --force